#!/usr/bin/env python3
"""PreToolUse on Write|Edit: refuse what violates an invariant silently.

Each pattern is here because its violation produces no error at the moment of
the mistake. A pattern whose omission shows at compile time or in tests has
nothing to do in a hook: it belongs in a rule.

Every pattern added here comes with its nominal case AND its false positive in
test_hooks.py. An overzealous hook ends up disabled, taking the true positives
with it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import protocole_hook as p  # noqa: E402

EVENT = "PreToolUse"

# The only crate allowed to depend on Tauri (I-08 / ADR-0029).
CRATE_TAURI = "crates/oxyn-desktop/"

# The only front-end module that calls `invoke` (I-01, rules/front.md).
CLIENT_IPC = "apps/desktop/src/lib/ipc/client.ts"

# Generated by `shadcn add`, never edited: its constructs are not ours, and a
# refusal there would block an `--overwrite` without protecting anything.
GENERATED_COMPONENTS = "apps/desktop/src/components/ui/"

# Forbidden catch-all names (CLAUDE.md § code organization).
CATCH_ALL = ("utils", "util", "common", "helpers", "misc", "divers", "shared")

# Types whose name announces a secret (I-03).
SECRET_NAME = r"(?:Credential|Secret|Password|Passwd|Token|ApiKey|Dsn|ConnectionString)"


def _code_lines(body: str) -> list[tuple[int, str]]:
    """Lines outside line comments. A `//` or `#` that *mentions* a forbidden
    pattern must not be refused: that is the main false positive."""
    result = []
    for number, line in enumerate(body.splitlines(), start=1):
        bare = line.strip()
        if bare.startswith("//") or bare.startswith("#") or bare.startswith("*"):
            continue
        result.append((number, line))
    return result


def verify_rust(rel: str, body: str) -> None:
    lines = _code_lines(body)

    # I-08 — Tauri outside the desktop host.
    # `drivers/` is covered just like `crates/`: driver crates live at the
    # repository root and need the invariant no less.
    if (rel.startswith("crates/") or rel.startswith("drivers/")) and not rel.startswith(CRATE_TAURI):
        for number, line in lines:
            if re.search(r"\buse\s+tauri\w*\b|\btauri\w*\s*::", line):
                p.deny(
                    EVENT,
                    f"I-08: {rel}:{number} imports Tauri, but only "
                    "`crates/oxyn-desktop/` may depend on it (ADR-0029). A "
                    "Tauri type in the core removes the CLI, headless tests and "
                    "the next interface change. Define the type in `oxyn-core` "
                    "and convert it in `oxyn-desktop`.",
                )

    # I-05 — a synchronous Tauri command runs on the main thread.
    # Checked on 2026-09-15 (docs/RESEARCH-NOTES.md § Tauri interface and front end): without
    # `async` or `#[tauri::command(async)]`, the window waits for the body.
    # `ask` and not `deny`: a command that only reads in-memory state may stay
    # synchronous, and only a human knows what the body calls.
    if rel.startswith(CRATE_TAURI):
        for block in re.finditer(
            r"#\[tauri::command\]\s*(?:#\[[^\]]*\]\s*)*(?:pub(?:\([^)]*\))?\s+)?fn\s+(\w+)",
            body,
        ):
            p.ask(
                EVENT,
                f"I-05: `{block.group(1)}` in {rel} is a synchronous Tauri "
                "command: Tauri 2 runs it on the main thread. A read of the "
                "store, the keychain or a batch spilled to disk freezes the "
                "window there. Write `async fn`, or `#[tauri::command(async)]` "
                "— unless the body only touches in-memory state.",
            )

    # I-03 — Debug derived on a secret carrier.
    for block in re.finditer(
        r"#\[derive\(([^)]*)\)\]\s*(?:pub(?:\([^)]*\))?\s+)?(?:struct|enum)\s+(\w+)",
        body,
    ):
        derived, item_name = block.group(1), block.group(2)
        if "Debug" in derived and re.search(SECRET_NAME, item_name):
            p.deny(
                EVENT,
                f"I-03: `#[derive(Debug)]` on `{item_name}` in {rel}. A derived "
                "`Debug` on a type carrying a secret leaks as soon as a "
                "`tracing::debug!(\"{...:?}\")` is added six months later — "
                "and that leak is invisible in review. Write `impl fmt::Debug` "
                "by hand, redacting the value (docs/SECURITY.md § secrets).",
            )

    # I-03 — hard-coded secret.
    for number, line in lines:
        if re.search(r"(?:postgres|postgresql|mysql|mongodb|redis|rediss)://[^\s\"']*:[^\s\"'@/]+@", line):
            p.deny(
                EVENT,
                f"I-03: {rel}:{number} contains a connection string with a "
                "cleartext password. It will be committed, and it is often "
                "real. Go through the configuration and the keychain "
                "(docs/SECURITY.md).",
            )

    # SECURITY § unsafe — an unsafe block without justification.
    for block in re.finditer(r"(?:\A|\n)([^\n]*)\n([^\n]*\bunsafe\s*\{)", body):
        previous, current = block.group(1), block.group(2)
        if "SAFETY:" not in previous and "SAFETY:" not in current:
            p.ask(
                EVENT,
                f"{rel} opens an `unsafe` block without a `// SAFETY:` comment "
                "right before it. The policy requires the invariant that makes "
                "the block correct and that will keep it true — not a "
                "paraphrase of the code (docs/SECURITY.md § `unsafe` policy).",
            )

    # CLAUDE.md — catch-all modules.
    for number, line in lines:
        matched = re.match(r"\s*(?:pub\s+)?mod\s+(\w+)\s*[;{]", line)
        if matched and matched.group(1).lower() in CATCH_ALL:
            p.ask(
                EVENT,
                f"{rel}:{number} declares `mod {matched.group(1)}`. A "
                "catch-all name is the symptom of a split nobody managed to "
                "make, and it becomes the universal coupling point of the "
                "crate. Name the module after its subject.",
            )


def verify_manifest(rel: str, body: str) -> None:
    """I-08 at the manifest level: the dependency before the import."""
    if not (rel.startswith("crates/") or rel.startswith("drivers/")):
        return
    for number, line in _code_lines(body):
        if not rel.startswith(CRATE_TAURI) and re.match(r"\s*tauri[\w-]*\s*(?:=|\.)", line):
            p.deny(
                EVENT,
                f"I-08: {rel}:{number} adds a Tauri dependency outside "
                "`crates/oxyn-desktop/` (ADR-0029). The interface toolkit "
                "would enter the core, and keeping it out is precisely what "
                "made leaving GPUI possible.",
            )


# The TODO check only applies to code. A document that *talks about* TODOs — a
# rule, a command, a checklist — legitimately contains some: this is a false
# positive seen in real use, and a false positive blocks the work every turn
# until the hook is disabled.
CODE_EXTENSIONS = (".rs", ".toml", ".py", ".wit", ".sql")

# The two accepted forms, and the same definition as `script/verifier-todo`,
# which applies the check to the whole repository in `make qualite`. A phase of
# the implementation plan counts as a date: the plan says what it contains, so
# when it arrives. If either definition moves, the other must follow —
# otherwise the hook refuses what the quality gate accepts.
DEADLINE_PATTERN = r"TODO\s*\(\s*(?:\d{4}-\d{2}-\d{2}|phase\s+\d+)"


def verify_front(rel: str, body: str) -> None:
    """The webview front end: what is written there compiles, passes the
    stories, and yet opens a path an injected script would take."""
    if not rel.startswith("apps/desktop/src/") or not rel.endswith((".ts", ".tsx")):
        return
    lines = _code_lines(body)

    # I-01 — a second caller of `invoke`. On the whole text, not line by line:
    # a multi-line import is the form Prettier produces. `Channel` or `isTauri`
    # imported from the same module remain allowed.
    if rel != CLIENT_IPC:
        code = "\n".join(line for _, line in lines)
        namespace = re.search(r"""import\s*\*\s*as\s+(\w+)\s+from\s*["']@tauri-apps/api/core["']""", code)
        if (
            re.search(r"""import\s*\{[^}]*\binvoke\b[^}]*\}\s*from\s*["']@tauri-apps/api/core["']""", code)
            or (namespace and re.search(rf"\b{namespace.group(1)}\s*\.\s*invoke\b", code))
            or "__TAURI_INTERNALS__" in code
        ):
            p.deny(
                EVENT,
                f"I-01: {rel} calls `invoke` outside `{CLIENT_IPC}`. Every "
                "caller of `invoke` is a path to the backend that is not "
                "audited with the others — and it is the one an XSS would "
                "take. Go through `call` from `src/lib/ipc/<domain>.ts` "
                "(.claude/rules/front.md).",
            )

    # Input surface — raw injected HTML.
    if not rel.startswith(GENERATED_COMPONENTS):
        for number, line in lines:
            if "dangerouslySetInnerHTML" in line:
                p.deny(
                    EVENT,
                    f"{rel}:{number} uses `dangerouslySetInnerHTML`. A cell, a "
                    "table name or a model response are hostile inputs; "
                    "rendered as HTML in the webview, they reach `invoke` and "
                    "therefore the backend (docs/SECURITY.md § Input "
                    "surface). Render React text.",
                )


def verify_code(rel: str, body: str) -> None:
    """Hygiene that applies to code only."""
    if not rel.endswith(CODE_EXTENSIONS):
        return
    for number, line in _code_lines(body):
        if re.search(r"\bTODO\b", line) and not re.search(DEADLINE_PATTERN, line):
            p.ask(
                EVENT,
                f"{rel}:{number} contains a `TODO` without a deadline. A TODO "
                "that does not say when will never be read again. Write "
                "`TODO(2026-09-05): what unblocks it` or `TODO(phase 2)`, or "
                "do the work now.",
            )


def main() -> None:
    event = p.read_event()
    if event.get("tool_name") not in ("Write", "Edit", "MultiEdit"):
        p.laisser_passer()

    rel = p.relative_path(p.tool_path(event))
    body = p.tool_content(event)
    if not rel or not body:
        p.laisser_passer()

    if rel.endswith(".rs"):
        verify_rust(rel, body)
    if rel.endswith("Cargo.toml"):
        verify_manifest(rel, body)
    verify_front(rel, body)
    verify_code(rel, body)
    p.laisser_passer()


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception:
        # A failing hook never interrupts the work.
        sys.exit(0)
