#!/usr/bin/env python3
"""PreToolUse on Write|Edit: refuse what violates an invariant silently.

Each pattern is here because its violation produces no error at the moment of
the mistake. A pattern whose omission shows at compile time or in tests has
nothing to do in a hook: it belongs in a rule.

Every pattern added here comes with its nominal case AND its false positive in
test_hooks.py. An overzealous hook ends up disabled, taking the true positives
with it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import protocole_hook as p  # noqa: E402

EVENEMENT = "PreToolUse"

# The only crate allowed to depend on Tauri (I-08 / ADR-0029).
CRATE_TAURI = "crates/oxyn-desktop/"

# The only front-end module that calls `invoke` (I-01, rules/front.md).
CLIENT_IPC = "apps/desktop/src/lib/ipc/client.ts"

# Generated by `shadcn add`, never edited: its constructs are not ours, and a
# refusal there would block an `--overwrite` without protecting anything.
COMPOSANTS_GENERES = "apps/desktop/src/components/ui/"

# Forbidden catch-all names (CLAUDE.md § code organization).
FOURRE_TOUT = ("utils", "util", "common", "helpers", "misc", "divers", "shared")

# Types whose name announces a secret (I-03).
NOM_SECRET = r"(?:Credential|Secret|Password|Passwd|Token|ApiKey|Dsn|ConnectionString)"


def _lignes_de_code(texte: str) -> list[tuple[int, str]]:
    """Lines outside line comments. A `//` or `#` that *mentions* a forbidden
    pattern must not be refused: that is the main false positive."""
    resultat = []
    for numero, ligne in enumerate(texte.splitlines(), start=1):
        nue = ligne.strip()
        if nue.startswith("//") or nue.startswith("#") or nue.startswith("*"):
            continue
        resultat.append((numero, ligne))
    return resultat


def verifier_rust(rel: str, texte: str) -> None:
    lignes = _lignes_de_code(texte)

    # I-08 — Tauri outside the desktop host.
    # `drivers/` is covered just like `crates/`: driver crates live at the
    # repository root and need the invariant no less.
    if (rel.startswith("crates/") or rel.startswith("drivers/")) and not rel.startswith(CRATE_TAURI):
        for numero, ligne in lignes:
            if re.search(r"\buse\s+tauri\w*\b|\btauri\w*\s*::", ligne):
                p.refuser(
                    EVENEMENT,
                    f"I-08: {rel}:{numero} imports Tauri, but only "
                    "`crates/oxyn-desktop/` may depend on it (ADR-0029). A "
                    "Tauri type in the core removes the CLI, headless tests and "
                    "the next interface change. Define the type in `oxyn-core` "
                    "and convert it in `oxyn-desktop`.",
                )

    # I-05 — a synchronous Tauri command runs on the main thread.
    # Checked on 2026-09-15 (docs/RESEARCH-NOTES.md § interface Tauri): without
    # `async` or `#[tauri::command(async)]`, the window waits for the body.
    # `ask` and not `deny`: a command that only reads in-memory state may stay
    # synchronous, and only a human knows what the body calls.
    if rel.startswith(CRATE_TAURI):
        for bloc in re.finditer(
            r"#\[tauri::command\]\s*(?:#\[[^\]]*\]\s*)*(?:pub(?:\([^)]*\))?\s+)?fn\s+(\w+)",
            texte,
        ):
            p.demander(
                EVENEMENT,
                f"I-05: `{bloc.group(1)}` in {rel} is a synchronous Tauri "
                "command: Tauri 2 runs it on the main thread. A read of the "
                "store, the keychain or a batch spilled to disk freezes the "
                "window there. Write `async fn`, or `#[tauri::command(async)]` "
                "— unless the body only touches in-memory state.",
            )

    # I-03 — Debug derived on a secret carrier.
    for bloc in re.finditer(
        r"#\[derive\(([^)]*)\)\]\s*(?:pub(?:\([^)]*\))?\s+)?(?:struct|enum)\s+(\w+)",
        texte,
    ):
        derives, nom = bloc.group(1), bloc.group(2)
        if "Debug" in derives and re.search(NOM_SECRET, nom):
            p.refuser(
                EVENEMENT,
                f"I-03: `#[derive(Debug)]` on `{nom}` in {rel}. A derived "
                "`Debug` on a type carrying a secret leaks as soon as a "
                "`tracing::debug!(\"{...:?}\")` is added six months later — "
                "and that leak is invisible in review. Write `impl fmt::Debug` "
                "by hand, redacting the value (docs/SECURITY.md § secrets).",
            )

    # I-03 — hard-coded secret.
    for numero, ligne in lignes:
        if re.search(r"(?:postgres|postgresql|mysql|mongodb|redis|rediss)://[^\s\"']*:[^\s\"'@/]+@", ligne):
            p.refuser(
                EVENEMENT,
                f"I-03: {rel}:{numero} contains a connection string with a "
                "cleartext password. It will be committed, and it is often "
                "real. Go through the configuration and the keychain "
                "(docs/SECURITY.md).",
            )

    # SECURITY § unsafe — an unsafe block without justification.
    for bloc in re.finditer(r"(?:\A|\n)([^\n]*)\n([^\n]*\bunsafe\s*\{)", texte):
        precedent, courant = bloc.group(1), bloc.group(2)
        if "SAFETY:" not in precedent and "SAFETY:" not in courant:
            p.demander(
                EVENEMENT,
                f"{rel} opens an `unsafe` block without a `// SAFETY:` comment "
                "right before it. The policy requires the invariant that makes "
                "the block correct and that will keep it true — not a "
                "paraphrase of the code (docs/SECURITY.md § politique unsafe).",
            )

    # CLAUDE.md — catch-all modules.
    for numero, ligne in lignes:
        correspondance = re.match(r"\s*(?:pub\s+)?mod\s+(\w+)\s*[;{]", ligne)
        if correspondance and correspondance.group(1).lower() in FOURRE_TOUT:
            p.demander(
                EVENEMENT,
                f"{rel}:{numero} declares `mod {correspondance.group(1)}`. A "
                "catch-all name is the symptom of a split nobody managed to "
                "make, and it becomes the universal coupling point of the "
                "crate. Name the module after its subject.",
            )


def verifier_manifeste(rel: str, texte: str) -> None:
    """I-08 at the manifest level: the dependency before the import."""
    if not (rel.startswith("crates/") or rel.startswith("drivers/")):
        return
    for numero, ligne in _lignes_de_code(texte):
        if not rel.startswith(CRATE_TAURI) and re.match(r"\s*tauri[\w-]*\s*(?:=|\.)", ligne):
            p.refuser(
                EVENEMENT,
                f"I-08: {rel}:{numero} adds a Tauri dependency outside "
                "`crates/oxyn-desktop/` (ADR-0029). The interface toolkit "
                "would enter the core, and keeping it out is precisely what "
                "made leaving GPUI possible.",
            )


# The TODO check only applies to code. A document that *talks about* TODOs — a
# rule, a command, a checklist — legitimately contains some: this is a false
# positive seen in real use, and a false positive blocks the work every turn
# until the hook is disabled.
EXTENSIONS_CODE = (".rs", ".toml", ".py", ".wit", ".sql")

# The two accepted forms, and the same definition as `script/verifier-todo`,
# which applies the check to the whole repository in `make qualite`. A phase of
# the implementation plan counts as a date: the plan says what it contains, so
# when it arrives. If either definition moves, the other must follow —
# otherwise the hook refuses what the quality gate accepts.
MOTIF_ECHEANCE = r"TODO\s*\(\s*(?:\d{4}-\d{2}-\d{2}|phase\s+\d+)"


def verifier_front(rel: str, texte: str) -> None:
    """The webview front end: what is written there compiles, passes the
    stories, and yet opens a path an injected script would take."""
    if not rel.startswith("apps/desktop/src/") or not rel.endswith((".ts", ".tsx")):
        return
    lignes = _lignes_de_code(texte)

    # I-01 — a second caller of `invoke`. On the whole text, not line by line:
    # a multi-line import is the form Prettier produces. `Channel` or `isTauri`
    # imported from the same module remain allowed.
    if rel != CLIENT_IPC:
        code = "\n".join(ligne for _, ligne in lignes)
        espace = re.search(r"""import\s*\*\s*as\s+(\w+)\s+from\s*["']@tauri-apps/api/core["']""", code)
        if (
            re.search(r"""import\s*\{[^}]*\binvoke\b[^}]*\}\s*from\s*["']@tauri-apps/api/core["']""", code)
            or (espace and re.search(rf"\b{espace.group(1)}\s*\.\s*invoke\b", code))
            or "__TAURI_INTERNALS__" in code
        ):
            p.refuser(
                EVENEMENT,
                f"I-01: {rel} calls `invoke` outside `{CLIENT_IPC}`. Every "
                "caller of `invoke` is a path to the backend that is not "
                "audited with the others — and it is the one an XSS would "
                "take. Go through `call` from `src/lib/ipc/<domain>.ts` "
                "(.claude/rules/front.md).",
            )

    # Input surface — raw injected HTML.
    if not rel.startswith(COMPOSANTS_GENERES):
        for numero, ligne in lignes:
            if "dangerouslySetInnerHTML" in ligne:
                p.refuser(
                    EVENEMENT,
                    f"{rel}:{numero} uses `dangerouslySetInnerHTML`. A cell, a "
                    "table name or a model response are hostile inputs; "
                    "rendered as HTML in the webview, they reach `invoke` and "
                    "therefore the backend (docs/SECURITY.md § surface "
                    "d'entrée). Render React text.",
                )


def verifier_code(rel: str, texte: str) -> None:
    """Hygiene that applies to code only."""
    if not rel.endswith(EXTENSIONS_CODE):
        return
    for numero, ligne in _lignes_de_code(texte):
        if re.search(r"\bTODO\b", ligne) and not re.search(MOTIF_ECHEANCE, ligne):
            p.demander(
                EVENEMENT,
                f"{rel}:{numero} contains a `TODO` without a deadline. A TODO "
                "that does not say when will never be read again. Write "
                "`TODO(2026-09-05): what unblocks it` or `TODO(phase 2)`, or "
                "do the work now.",
            )


def principal() -> None:
    evenement = p.lire_evenement()
    if evenement.get("tool_name") not in ("Write", "Edit", "MultiEdit"):
        p.laisser_passer()

    rel = p.chemin_relatif(p.chemin_outil(evenement))
    texte = p.contenu_outil(evenement)
    if not rel or not texte:
        p.laisser_passer()

    if rel.endswith(".rs"):
        verifier_rust(rel, texte)
    if rel.endswith("Cargo.toml"):
        verifier_manifeste(rel, texte)
    verifier_front(rel, texte)
    verifier_code(rel, texte)
    p.laisser_passer()


if __name__ == "__main__":
    try:
        principal()
    except SystemExit:
        raise
    except Exception:
        # A failing hook never interrupts the work.
        sys.exit(0)
