[package]
name = "oxyn-driver-postgres"
description = "Driver PostgreSQL (et dialectes compatibles : Redshift, Timescale, pgvector)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
oxyn-core.workspace = true
oxyn-catalog.workspace = true
oxyn-data.workspace = true
oxyn-driver.workspace = true
arrow.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
secrecy.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
