//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"
import storybook from "eslint-plugin-storybook"

export default [
  ...tanstackConfig,
  ...storybook.configs["flat/recommended"],
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    ignores: [
      "eslint.config.js",
      ".prettierrc",
      "dist/**",
      "storybook-static/**",
      "src/routeTree.gen.ts",
      // Generated by `shadcn add` and regenerated on update: linting it
      // against this project's style would turn every shadcn update into a
      // diff nobody reviews. Our own components live in `src/components/oxyn`.
      "src/components/ui/**",
      "src/hooks/use-mobile.ts",
    ],
  },
]
